// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTB5AujsPIrnALAiBDCzi_mi2DQDcmFWM',
    appId: '1:865644978542:web:a1b0ea2c07060eef6fa17f',
    messagingSenderId: '865644978542',
    projectId: 'kynex-b687f',
    authDomain: 'kynex-b687f.firebaseapp.com',
    storageBucket: 'kynex-b687f.firebasestorage.app',
    measurementId: 'G-WPNRM2BREV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwe7FFmF6PSADRn08eo-b6aFFRec_tZqA',
    appId: '1:865644978542:android:929704ecfb8fae9c6fa17f',
    messagingSenderId: '865644978542',
    projectId: 'kynex-b687f',
    storageBucket: 'kynex-b687f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdCVwE23XpcDv6W0_GWTNWVqtLgsBU0XY',
    appId: '1:865644978542:ios:29feb806bb1f556a6fa17f',
    messagingSenderId: '865644978542',
    projectId: 'kynex-b687f',
    storageBucket: 'kynex-b687f.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTB5AujsPIrnALAiBDCzi_mi2DQDcmFWM',
    appId: '1:865644978542:web:49934b989f5faf766fa17f',
    messagingSenderId: '865644978542',
    projectId: 'kynex-b687f',
    authDomain: 'kynex-b687f.firebaseapp.com',
    storageBucket: 'kynex-b687f.firebasestorage.app',
    measurementId: 'G-K0BJ9DB85C',
  );
}
